### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [KIOS-Research/QVisualize#1]
The functionality described in the About seems already present in core QGIS.
Please clarify what the plugin is actually adding.
Sorry for bothering, but we are trying hard not to duplicate functionality, so to reduce confusion for the users and administrative burden.
Thanks.

**Comment by Mariosmsk** [comment]
@pcav, where is this functionality? I agree to avoid duplicates. 
![image](https://user-images.githubusercontent.com/2945956/49644035-f66bf300-fa1f-11e8-8cc5-056dc1f46734.png)

Especially, you can select the point layer for visualizing, select the time delay (in seconds) to appear the next feature and select to show the final/current feature or show the final feature with historical features. For the next version, we will add the option to the user to add a link with live data to show on the map. So, I'll leave the plugin here and I'll enrich it soon.

Thanks,
Marios

**Comment by pcav** [comment]
From the description:
"Visualize a point layer on canvas map. For example, you can visualize a car/bird/boat or anything you want."
What is new, AFAICT, is that the points are loaded one by one, right?
In this case, a more descriptive About would do.
Thanks.

**Comment by Mariosmsk** [comment]
I have made changes in the About: "This tool can be used to visualize the features of a point layer one by one. Specifically, you can select a point layer to be visualized, then select the desired time delay (in seconds) and the accumulative or current only display. Then the point features in the layer will appear one by one according. You can use it for example to visualize a moving car/bird/boat etc."

QVisualize:  https://goo.gl/qdtT2D (youtube video)

**Comment by pcav** [comment]
Please commit to the repo. Currently the About on https://plugins.qgis.org is unchanged.
Thanks.

**Comment by Mariosmsk** [comment]
I have uploaded it now as version 0.3
